name: Build Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: portfolio/profile_JustinOngWay

      - name: Build Jekyll Site
        run: |
          docker run --rm \
            --volume="$PWD:/srv/jekyll" \
            -it jekyll/jekyll:latest \
            jekyll build
